#
# Macro file for the initialization phase of "radioActiv.cc"
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
/run/verbose 2
#
/run/initialize
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 1000x1000-0+0
#/vis/open OGL 600x600-0+0

#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
#/vis/viewer/set/viewpointThetaPhi 70. 30.
#/vis/viewer/set/viewpointThetaPhi 65. 33.9
/vis/viewer/set/viewpointThetaPhi 70 35
#/vis/viewer/set/viewpointThetaPhi 90 45
#/vis/viewer/set/viewpointThetaPhi 90 89.9999

#
# Specify zoom value:
/vis/viewer/zoom 1.3
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#
# Draw coordinate axes:
#/vis/scene/add/axes 3 -1.5 -1 1 cm
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 20

#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#//vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add e+
#

/vis/viewer/set/background white
/vis/viewer/set/globalLineWidthScale 1.0
/vis/viewer/set/defaultColour black
/vis/modeling/trajectories/drawByCharge-0/default/setLineWidth 1.00
#특이한건 이거 scale이 1.5, 2.5 단위로 변하는듯

# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set nu_e yellow
/vis/modeling/trajectories/drawByParticleID-0/set anti_nu_e red
/vis/modeling/trajectories/drawByParticleID-0/set geantino white
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set alpha yellow
/vis/modeling/trajectories/drawByParticleID-0/set GenericIon magenta
/vis/modeling/trajectories/drawByParticleID-0/set Ne22 cyan
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton green
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

#/vis/scene/add/fieldLines
/vis/viewer/set/style s
/vis/viewer/refresh
/vis/viewer/set/hiddenEdge 1
/vis/viewer/refresh
#/vis/scene/add/magneticField 30
#/vis/scene/add/magneticField 15

#/vis/scene/add/magneticField 30 lightArrow
#/vis/scene/modeling/arrow/setLengthScale 5.0
#/vis/scene/modeling/arrow/setWidthScale 1.0
# Re-establish auto refreshing and verbosity:

#/vis/viewer/flush
#/vis/ogl/set/exportFormat png
#/vis/ogl/set/printMode pixmap
#/vis/ogl/set/printSize 2000 2000
#/vis/ogl/set/printFilename hello.png
#/vis/ogl/export

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
